name: Node CD

on: [push, pull_request]

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        npm ci
    - name: build application
      run: |
        npm run build
    - name: Deploy on Github Pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: build